[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = ['pip install -r server/requirements.txt']

[phases.build]
cmds = ['echo "Flask backend ready for deployment"']

[start]
cmd = 'python server/app.py'